version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:16.18

jobs:
  contract-test:

    executor: my-custom-executor
    working_directory: ~/token-bridge-contracts
    steps:
      - checkout
      - run: |
          yarn install
          yarn build
          yarn test

workflows:
  my-custom-workflow:
    jobs:
      - contract-test